# Find more information on toml format here:  https://github.com/toml-lang/toml

# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[31,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="https://github.com/TheFabulousCube/Paragonia-1.15/issues" #optional

# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory

modId="paragonia" #mandatory
version="0.6.8-alpha" #mandatory ${file.jarVersion}
displayName="Paragonia" #mandatory
updateJSONURL="https://raw.githubusercontent.com/TheFabulousCube/Paragonia-1.15/master/src/main/resources/update.json" #optional
displayURL="https://github.com/TheFabulousCube/Paragonia-1.15" #optional
logoFile="pack.png" 
credits="All artwork and design by Elsweyr" 
authors="The Fabulous Cube" 

description="Mod pack designed to supplement Paragonia Texture pack"
 
[[dependencies.paragonia]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[31,)" #mandatory
    ordering="NONE"
    side="BOTH"
 
[[dependencies.paragonia]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
